FROM ubuntu:focal

ADD . /opt/envsetup-lite
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive
ARG DO_ALL=false
ARG DO_PYTHON=true
ARG DO_ENV=true
ARG DO_VIM=true
ARG DO_EXTRAS=true
ARG DO_DOCKER=false
ARG DO_DESKTOP=false
ARG ALLOW_SUDO=false
ARG DO_BREW_IF_NO_SUDO=true

RUN apt-get update --fix-missing
RUN apt-get install --yes curl sudo
RUN apt-get clean
RUN useradd -m testuser -s /bin/bash

USER testuser
RUN whoami
RUN sudo whoami || true
RUN cd /home/testuser \
    && cp -r /opt/envsetup-lite . \
    && cd envsetup-lite \
    && /bin/bash set_up.sh

